name: Update Comments

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update comments.json
        run: |
          echo $INPUT_NEW_COMMENTS > comments.json
          git config --global user.email "you@example.com"
          git config --global user.name "GitHub Actions"
          git add comments.json
          git commit -m "Update comments.json"
          git push
