name: Update Comments
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Job 1: Prepare and update comments
  prepare-update:
    runs-on: ubuntu-latest
    steps:
      # Free up disk space FIRST
      - name: Free up disk space
        run: |
          echo "Initial disk usage:"
          df -h
          echo "Cleaning up..."
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo apt-get clean
          echo "After cleanup:"
          df -h
      
      # Use newer checkout action
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1  # Shallow clone to save space
      
      - name: Update comments file
        run: |
          echo "Here you can run scripts to manipulate your comments.json or other tasks"
          mkdir -p temp
          echo "Temporary data" > temp/temp.txt
      
      # Delete temp files immediately after use
      - name: Clean temporary files
        if: always()
        run: |
          rm -rf ./temp
      
      - name: Commit changes
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          if ! git diff --quiet || ! git diff --staged --quiet; then
            git add -A
            git commit -m "Update comments.json"
            git push
          else
            echo "No changes to commit"
          fi
      
      - name: Show final disk usage
        if: always()
        run: df -h

  # Job 2: Optional Docker-heavy tasks (isolated)
  docker-tasks:
    runs-on: ubuntu-latest
    needs: prepare-update
    steps:
      # Free up disk space FIRST for Docker job
      - name: Free up disk space
        run: |
          echo "Initial disk usage:"
          df -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo docker system prune -af
          sudo apt-get clean
          echo "After cleanup:"
          df -h
      
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      
      - name: Run Docker-related tasks
        run: |
          echo "Building Docker images or running container tasks..."
          # Example: docker build -t myimage .
      
      # Clean Docker immediately after use
      - name: Clean Docker
        if: always()
        run: |
          sudo docker system prune -af --volumes || true
          sudo rm -rf /var/lib/docker/tmp/*
      
      - name: Show final disk usage
        if: always()
        run: df -h
